let report="*******Report card of the student*******";
let name="name:Aadrsh singh";
let school="school:SSM";
let section="section:A";
let roll_no="roll no:17207211";
let grade="grade:9";
let x="marks scored by student in three subject";
let m="maths  :90";
let p="physics:90";
let e="english:90";
console.log(report);
console.log(name);
console.log(school);
console.log(section);
console.log(roll_no);
console.log(grade);
console.log(x);
console.log(m);
console.log(p);
console.log(e);